stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  NEXUS_REPO_ID: "nexus-repo"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master

