stages:
  - build
  - test
  - package
  - deploy-tomcat
  - deploy-nexus

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  TOMCAT_HOST: "localhost"
  TOMCAT_PORT: "http://localhost:8080"
  TOMCAT_USERNAME: "admin1"
  TOMCAT_PASSWORD: "admin1"

before_script:
  - dnf install -y maven

build:
  stage: build
  script:
    - echo "Running the build job"
    - mvn clean compile

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package

deploy-tomcat:
  stage: deploy-tomcat
  script:
    - mvn tomcat7:deploy

deploy-nexus: 
  stage: deploy-nexus
  script:  
    - mvn deploy -DrepositoryId=nexus-releases -Durl=http://localhost:8081/repository/maven-releases/ -Dversion=5.3.8 -DgroupId=Gitlab.example -DartifactId=my-artifact -Dpackaging=war
