image: maven:3-jdk-11

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  TOMCAT_HOST: "83.83.42.214"
  TOMCAT_PORT: "http://localhost:8080/"
  TOMCAT_USERNAME: "admin1"
  TOMCAT_PASSWORD: "admin1"

before_script:
  - dnf update -y
  - dnf install -y maven

build:
  stage: build
  script: "mvn install -B"
  script:
    - mvn clean package

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - mvn package
    - cp /home/andychen/devoteam-traineeship-petclinic/target/petclinic.war /opt/apache-tomcat-9.0.76/webapps
     - echo "Deploying to production server"
    - curl --upload-file /home/andychen/devoteam-traineeship-petclinic/target/petclinic.war  "http://$admin1:$admin1@$83.83.42.214:$TOMCAT_PORT/manager/text/deploy?/home/andychen/devoteam-traineeship-petclinic/target/petclinic.war&update=true"

