trigger:
  branches:
    include:
      - master

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - stage: load_test
    displayName: 'Load Test'
    jobs:
      - job: load_test
        displayName: 'JMeter Load Test Job'
        pool: Petclinic
        steps:
          - script: |
              # Remove the existing 'load-test-repo' directory if it exists
              rm -rf $(Pipeline.Workspace)/load-test-repo

              # Clone the JMeter test plan repository into the workspace
              git clone https://github.com/andychen96/petclinic-devo.git $(Pipeline.Workspace)/load-test-repo

              # Run the JMeter load test using the locally installed JMeter
              jmeter -n -t $(Pipeline.Workspace)/load-test-repo/load-test.jmx -l $(Pipeline.Workspace)/results.jtl
            displayName: 'Run JMeter Tests'

          - task: PublishTestResults@2
            displayName: 'Publish JMeter Test Results'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '$(Pipeline.Workspace)/results.jtl'
              failTaskOnFailedTests: true


